### ISSUE TITLE
delete_file_locations support

### ISSUE THREAD

**Issue by bwalsh** [ACED-IDP/gen3_util#27]
https://ohsucomputationalbio.slack.com/archives/C043HPV0VMY/p1700260682334969

Liam Beckman
  [2:38 PM](https://ohsucomputationalbio.slack.com/archives/C043HPV0VMY/p1700260682334969)
Hi all, we’re plugging along on the [aced-idp.org](http://aced-idp.org/) data portal and are running into an issue when attempting to delete indexd records using the Gen3 SDK. I’ve included additional info below on that, but let us know if we can add anything else or try to reproduce the issue, thank you!
 
Issue:
When attempting to delete an indexd record using the [delete_file_locations() ](https://uc-cdis.github.io/gen3sdk-python/_build/html/file.html#gen3.file.Gen3File.delete_file_locations)method in the Gen3 SDK, we encounter a “The AWS Access Key Id you provided does not exist” error. The indexd record is in non-AWS S3 bucket (MinIO endpoint), which is specified by the endpoint_url of the bucket in the Fence config.
 
Expected Behavior:
The [delete_file_locations() ](https://uc-cdis.github.io/gen3sdk-python/_build/html/file.html#gen3.file.Gen3File.delete_file_locations)method should delete both the file and the indexd record for both AWS and non-AWS S3-compatible buckets. (edited)

**Comment by bwalsh** [comment]
See https://github.com/ACED-IDP/gen3_util/pull/26

**Comment by lbeckman314** [comment]
Testing file removal on Local and Development deployments using the following:
- Fence PR: https://github.com/uc-cdis/fence/pull/1127
- `gen3_util files rm`: https://github.com/ACED-IDP/gen3_util/commit/f831d498f52dc80ef8ae7dfbc723a7206dc431a9

**Comment by bwalsh** [comment]
@lbeckman314 if all OK, can you close this issue?  thanks

**Comment by lbeckman314** [comment]
Closed as complete, see the following PR for status on upstream merging:
> https://github.com/uc-cdis/fence/pull/1127#issuecomment-1910907456
