### ISSUE TITLE
dataframer:  include condition in Observation dataframe

### ISSUE THREAD

**Issue by bwalsh** [ACED-IDP/gen3_util#79]
> Looking to add cancer type / biopsy location to the FHIR labkey metadata. Looking through the labkey data it seems like this information can be gained by joining via patient id the enrollment table to the sequencing table. How would you approach this?

Assumptions:
* a Condition MAY exist - creating the condition is the responsibility of the data submitter, the condition may be created in any fashion; by hand, by a g3t_etl transformer or other mechanism.

Approach:
* The subject of the observation is called [here](https://github.com/ACED-IDP/gen3_util/blob/feature/git/gen3_tracker/meta/dataframer.py#L340-L345) if the subject is a Patient
* Note that the condition is not mapped directly from the [observation](https://www.hl7.org/fhir/observation-definitions.html#Observation).  There can be several paths from Observation to Condition via   Observation.focus:
    * [Procedure](https://www.hl7.org/fhir/procedure-definitions.html#Procedure.reason)
    * [Patient->Condition](https://www.hl7.org/fhir/condition-definitions.html#Condition.subject)

Effectively the "join" is observation.subject == condition.subject :
  * Items from the patient should be mapped to the observation similar to how [fields from a linked Procedure is mapped](https://github.com/ACED-IDP/gen3_util/blob/feature/git/gen3_tracker/meta/dataframer.py#L352-L355)
  * This may be overly simplistic as the patient can have multiple conditions, however this will get the basic observation dataframe populated

**Comment by matthewpeterkort** [comment]
See https://github.com/ACED-IDP/gen3_util/pull/80

**Comment by quinnwai** [comment]
merged PR #95 and commit 8733923 might be relevant here
